name: Generate Error Codes

on:
  push:
    branches: [main]

jobs:
  dispatch-domains:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Dispatch Go
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: generate-errors
          client-payload: '{"commit-message": "${{ github.event.head_commit.message }}"}'

      - name: Dispatch TypeScript
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: generate-errors
          client-payload: '{"commit-message": "${{ github.event.head_commit.message }}"}'