name: Generate Error Codes

on:
  push:
    paths:
      - 'errors/errors.json'
  workflow_dispatch:

jobs:
  generate-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go-errors/go.mod
          cache-dependency-path: go-errors/go.sum

      - name: Set up Pnpm
        uses: pnpm/action-setup@v2
        with:
          package_json_file: ts-errors/package.json
          run_install: false

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ts-errors/package.json
          cache: pnpm
          cache-dependency-path: ts-errors/pnpm-lock.yaml

      - name: Install Go dependencies
        run: go mod download
        working-directory: ./go-errors

      - name: Generate Golang errors
        run: go run generate.go
        working-directory: ./go-errors

      - name: Generate TypeScript errors
        run: pnpm prepublishOnly
        working-directory: ./ts-errors

      - name: Install TypeScript dependencies
        run: pnpm install
        working-directory: ./ts-errors

      - name: Create App Token
        id: generate-token
        uses: tibdex/github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: "chore: update error codes"
          title: "chore: update error codes"
          body: "This PR updates the error codes. Merging this PR will trigger deployments for Go and TypeScript domains."
          branch: "update-error-codes"
          team-reviewers: "api-maintainers"